version: '3.9'

services:
  mysql:
    image: mysql:8.0.32
    container_name: db_php
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uptask
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql_spring:/var/lib/mysql

volumes:
  mysql_spring:
    external: false
